name: Code Scanner

on:
  push:
    branches: 
      - '*'
jobs:
  secScan:
    name: Security Template
    uses: Security-Template/sec-template/.github/workflows/secTemplate.yml@main
    with:
      codeScannerRef: main